language: cpp

# Build matrix.
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang

# Use Ubuntu 14.04 as the build environment.
sudo: required
dist: trusty

# Build dependencies.
addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
      - nettle-dev
      - libudev-dev
      - qtbase5-dev

# Run the build script.
script: ./travis.sh

notifications:
  irc: "ircs://irc.badnik.zone:6697/#GensGS"
