# AppVeyor configuration file.
version: '1.1.1.{build}'

# Build worker image (VM template)
image: Visual Studio 2013

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\rvthtool

# Don't build if source files aren't modified.
only_commits:
  files:
    - appveyor.cmd
    - appveyor.yml
    - '**/CMakeLists.txt'
    - '**/*.cmd'
    - '**/*.sh'
    - extlib/**/*
    - src/**/*

environment:
  matrix:
    - platform: x86
      configuration: Debug
      compiler: msvc2013

    - platform: x86
      configuration: Release
      compiler: msvc2013

    - platform: x64
      configuration: Debug
      compiler: msvc2013

    - platform: x64
      configuration: Release
      compiler: msvc2013

    - platform: x86
      configuration: Debug
      compiler: mingw-w64

    - platform: x64
      configuration: Debug
      compiler: mingw-w64

# Run CMake.
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor.cmd

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake --build . --config %configuration%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest -V -C %configuration%

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ..\appveyor-artifacts.cmd
